[phases.setup]
nixPkgs = ["gcc", "openssl", "pkg-config"]

[phases.install]
cmds = ["echo 'Skipping install phase'"]

[phases.build]
cmds = ["cargo build --release"]

[start]
cmd = "./target/release/simulation-bot"
